Backend - portfolio - get user's portfolio
DaraghK93/stockApp pull request #540
Opened 2022-11-24 18:17 UTC by DaraghK93

This is the route and controller for getting the user's game portfolio. 

This will be used in a number of places. two of which are:
- on the game screen, to get the portfolio for the user to view
- on the trade page, so the user can see what they have in that portfolio - balance, holdings, how much of a stock they can sell etc.

The route is portfolio/:userId/:leagueId

we will have both of these in redux, or at least the user Id, and the gameId will be selected when they click onto the game, or click the dropdown with that game on the trade page.

2022-11-24 18:57 UTC, WarrenK-design requested changes
Hi Daragh, 

Just one small change and sorry should of spotted iton call we had earlier, we never store the user ID on the frontend, we store the JWT. 

Could you change this to ```GET /api/portoflio/:portfolioID``` and then as it is a protected route get the UserID from the JWT like the other routes?

2022-11-24 18:57 UTC, WarrenK-design commented on amplify/backend/function/expressServer/src/controllers/portfolioController.js
> +    if(req.user.id !== req.params.userId){
This check isn't needed if we get the userID from the auth middleware instead I think. The request will never get this far if unauthorised and middleware will catch this. If we remove userID then too from route like in suggestion wont have to check req.params.userId either.

2022-11-24 20:33 UTC, DaraghK93 commented
Thanks @WarrenK-design, that's fixed now

2022-11-24 20:35 UTC, DaraghK93 commented
@joeycor92  when you're looking at this, the route has changed to api/portfolio/:leagueId

2022-11-28 10:50 UTC, WarrenK-design commented
Hi Daragh, 

Think I'm running into problem Joey was. 

So Ive created a league. 
```json
{"_id":{"$oid":"63848e126d26665cc1d32fe3"},"leagueName":"The Big Stock League","startingBalance":1000,"leagueType":"valueBased","private":true,"active":false,"finished":false,"startDate":{"$date":"2022-12-31T00:00:00.000Z"},"winningValue":1001,"sectors":["Basic Materials","Communication Services","Consumer Cyclical","Consumer Defensive"],"maxDailyTrades":10,"tradingFee":10,"minERating":0,"minSRating":0,"minGRating":0,"accessCode":"hpzvk9","image":"/stock_photo_1.jpg","leagueAdmin":{"$oid":"63848d4b6d26665cc1d32fd8"},"users":[{"$oid":"63848d4b6d26665cc1d32fd8"}],"portfolios":[{"$oid":"63848e126d26665cc1d32fe5"}],"__v":0}
```
This did make a portfolio then too. 
```json
{"_id":{"$oid":"63848e126d26665cc1d32fe5"},"portfolioName":"The Big Stock League Portfolio","remainder":1000,"startingBalance":1000,"holdings":[],"dateCreated":{"$date":"2022-11-28T10:31:46.473Z"},"transactions":[],"leagueId":{"$oid":"63848e126d26665cc1d32fe3"},"userId":{"$oid":"63848d4b6d26665cc1d32fd8"},"tradesToday":0,"valueHistory":[],"__v":0}
```

Im sending the request ``` GET /api/portfolio/:leagueId``` with auth token in the header but it returns ```No portfolio found```.
![image](https://user-images.githubusercontent.com/61060096/204257768-8c47f52d-bbc5-4668-8ca2-33c595d3af38.png)

The controller does get the league ID and the User ID but the mongo query seems to return ```[ ]```

![image](https://user-images.githubusercontent.com/61060096/204258481-f2dc9333-7c6b-4c1b-a9da-587d36fd9e92.png)

Its this code which is being hit. 

![image](https://user-images.githubusercontent.com/61060096/204258642-45306003-85a3-475f-992f-a6ee8a8ded9e.png)

I ran the query too just directly on Mongo and seems to be returning ```[ ]``` too. 

![image](https://user-images.githubusercontent.com/61060096/204259521-4ab3053e-cd01-4997-a050-037a57d539d3.png)

2022-11-28 11:53 UTC, WarrenK-design approved these changes
Looks good Daragh, all working now after adding views locally.

2022-11-28 12:00 UTC, merged