updated tickercards
DaraghK93/stockApp pull request #583
Opened 2022-12-04 13:19 UTC by beckskelly

Had  go updating the tickercards,-
1. made the logos a bit bigger
2. put %change first and in bold, some are still a bit problematic

![image](https://user-images.githubusercontent.com/78801723/205492803-ab9bfd23-d086-46a5-adee-68cf44f35d7a.png)

2022-12-05 11:50 UTC, WarrenK-design requested changes
Hi Becks, 

Looks good cheers for that, just small thing getting few warnings for unused components/duplicate keys. 
![image](https://user-images.githubusercontent.com/61060096/205627944-d0568f0d-2802-4730-ba68-2f1f482bc42e.png)

# Formattting 
Just small thing too we noticed on Friday with numbers not being formatted correctly. 
![image](https://user-images.githubusercontent.com/61060096/205629986-8d5ef353-7c2e-49d6-93e9-d1cff34a73d5.png)

Could you change this code (Lines 13 to 24). 
```
function redOrGreen() {
    if (parseFloat(stock.daily_change.percentageChange) >= 0) {
      postiveSymbol = "+"
      absoluteChange = "$" + parseFloat(stock.daily_change.absoluteChange).toFixed(2)
      return "green"
    }
    else {
      var myString = String(stock.daily_change.absoluteChange)
      absoluteChange = myString.slice(0, 1) + "$" + myString.slice(1)
      return "red"
    }
  }
```
To code below, think it will solve it. 
```
function redOrGreen() {
    absoluteChange = parseFloat(stock.daily_change.absoluteChange).toLocaleString('en-US', { style: 'currency', currency: 'USD' })
    if (parseFloat(stock.daily_change.percentageChange) >= 0) {
      postiveSymbol = "+"
      return "green"
    }
    else {
      return "red"
    }
  }
```

2022-12-05 11:50 UTC, WarrenK-design commented on src/components/stockDiscoveryComponents/tickercard/Tickercard.js
> +        {/* <Container className="tickerCardImgContainer" style={{ margin: "none", paddingLeft: 0, paddingRight: 0, paddingTop: 0 }}>
I think we can delete these if not being used anymore

2022-12-05 13:20 UTC, beckskelly commented
Cheers @WarrenK-design , good spots, those changes should be pushed now

2022-12-05 16:34 UTC, WarrenK-design approved these changes
Looks good,  cheers Becks

2022-12-06 10:47 UTC, beckskelly commented
Swapped the card info around in line with the chat in discord and with other trading platforms: 

![image](https://user-images.githubusercontent.com/78801723/205891015-4215b126-d5d9-412a-b59d-6dbc4ea5d505.png)

2022-12-06 11:12 UTC, joeycor92 approved these changes
Happy with this now. From our chat yesterday it does make sense to have the absolute change first! Thanks.

2022-12-06 11:37 UTC, merged